"""path is Text

Revision ID: 280bb920ae91
Revises: c130671b95a5
Create Date: 2026-03-24 07:23:08.471657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '280bb920ae91'
down_revision = 'c130671b95a5'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_event', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_event', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###

