"""create

Revision ID: 83fee793a6ec
Revises: 
Create Date: 2026-03-13 14:52:22.670561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fee793a6ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_suppression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('exception_type', sa.String(length=512), nullable=False),
    sa.Column('last_alerted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_name', 'exception_type', name='uq_app_exc')
    )
    op.create_table('log_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('exception_type', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_event_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_event_exception_type'), ['exception_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_event_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('sns_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('notification_type', sa.String(length=64), nullable=True),
    sa.Column('topic_arn', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=256), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    with op.batch_alter_table('sns_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sns_notification_received_at'), ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sns_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sns_notification_received_at'))

    op.drop_table('sns_notification')
    with op.batch_alter_table('log_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_event_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_log_event_exception_type'))
        batch_op.drop_index(batch_op.f('ix_log_event_app_name'))

    op.drop_table('log_event')
    op.drop_table('alert_suppression')
    # ### end Alembic commands ###

