"""add disk_snapshot table

Revision ID: 8605b00fe4cf
Revises: 280bb920ae91
Create Date: 2026-03-31 12:03:16.634050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8605b00fe4cf'
down_revision = '280bb920ae91'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disk_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('mount', sa.String(length=512), nullable=False),
    sa.Column('device', sa.String(length=256), nullable=True),
    sa.Column('total_kb', sa.BigInteger(), nullable=True),
    sa.Column('used_kb', sa.BigInteger(), nullable=True),
    sa.Column('avail_kb', sa.BigInteger(), nullable=True),
    sa.Column('use_pct', sa.Integer(), nullable=True),
    sa.Column('docker_images_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('docker_images_reclaimable_bytes', sa.BigInteger(), nullable=True),
    sa.Column('docker_images_active', sa.Integer(), nullable=True),
    sa.Column('docker_containers_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('docker_containers_active', sa.Integer(), nullable=True),
    sa.Column('docker_volumes_count', sa.Integer(), nullable=True),
    sa.Column('docker_volumes_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('docker_volumes_reclaimable_bytes', sa.BigInteger(), nullable=True),
    sa.Column('docker_build_cache_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('docker_build_cache_reclaimable_bytes', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mount', 'collected_at', name='uq_disk_mount_ts')
    )
    with op.batch_alter_table('disk_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disk_snapshot_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disk_snapshot_mount'), ['mount'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disk_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disk_snapshot_mount'))
        batch_op.drop_index(batch_op.f('ix_disk_snapshot_collected_at'))

    op.drop_table('disk_snapshot')
    # ### end Alembic commands ###

