"""add mem_snapshot

Revision ID: 867128644022
Revises: 8605b00fe4cf
Create Date: 2026-04-25 06:30:15.495735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867128644022'
down_revision = '8605b00fe4cf'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mem_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('mem_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('mem_available_kb', sa.BigInteger(), nullable=True),
    sa.Column('mem_used_kb', sa.BigInteger(), nullable=True),
    sa.Column('mem_pct', sa.Integer(), nullable=True),
    sa.Column('swap_total_kb', sa.BigInteger(), nullable=True),
    sa.Column('swap_free_kb', sa.BigInteger(), nullable=True),
    sa.Column('swap_used_kb', sa.BigInteger(), nullable=True),
    sa.Column('swap_pct', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collected_at', name='uq_mem_ts')
    )
    with op.batch_alter_table('mem_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mem_snapshot_collected_at'), ['collected_at'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mem_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mem_snapshot_collected_at'))

    op.drop_table('mem_snapshot')
    # ### end Alembic commands ###

