"""add access_event table

Revision ID: c130671b95a5
Revises: 83fee793a6ec
Create Date: 2026-03-18 13:38:05.511476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c130671b95a5'
down_revision = '83fee793a6ec'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('ip_chain', sa.String(length=256), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('bytes_sent', sa.Integer(), nullable=True),
    sa.Column('referer', sa.String(length=1024), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_event_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_event_client_ip'), ['client_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_event_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_event_status_code'), ['status_code'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_event_status_code'))
        batch_op.drop_index(batch_op.f('ix_access_event_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_access_event_client_ip'))
        batch_op.drop_index(batch_op.f('ix_access_event_app_name'))

    op.drop_table('access_event')
    # ### end Alembic commands ###

